version: '3'

services:
  bluesys_db:
    image: mysql:5.7
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    ports:
      - '3308:3306'
    environment:
      MYSQL_DATABASE: db_bluesystem
      MYSQL_ROOT_USER: bluesys_user
      MYSQL_USER: bluesys_user
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
